#!/bin/sh

echo [Installer] Installing vim-plug...
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo To finish process, go to vim and type ':PlugInstall'
